/* Minimal Web Push sender for the Cloudflare Workers runtime.
 *
 * There is no npm `web-push` here on purpose — it's a Node package and won't
 * run in the Workers runtime. Everything below is built on the Workers-native
 * Web Crypto API (`crypto.subtle`) and implements exactly two RFCs:
 *   - RFC 8292 (VAPID): an ES256-signed JWT identifies this server to the push service.
 *   - RFC 8291 (Web Push encryption) + RFC 8188 (aes128gcm): the notification
 *     payload is encrypted so only the subscribed browser can read it.
 *
 * Kept in its own file because it's dense, self-contained, and should not need
 * to change when the two /subscribe and /scheduled call sites in index.js do.
 */

function b64urlToBytes(s) {
  const pad = s.length % 4 === 0 ? '' : '='.repeat(4 - (s.length % 4));
  const bin = atob(s.replace(/-/g, '+').replace(/_/g, '/') + pad);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
function bytesToB64url(bytes) {
  let bin = '';
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
function concatBytes(...arrs) {
  const len = arrs.reduce((n, a) => n + a.length, 0);
  const out = new Uint8Array(len);
  let off = 0;
  for (const a of arrs) { out.set(a, off); off += a.length; }
  return out;
}
const enc = s => new TextEncoder().encode(s);

/* ---------- VAPID (RFC 8292) ---------- */

/* privateKeyJwk is the full JWK (kty/crv/x/y/d) generated by
   worker/scripts/generate-vapid-keys.mjs and stored as the VAPID_PRIVATE_KEY
   secret. x/y aren't sensitive on their own (the public key is public by
   definition) — only `d` is, and it never leaves this JWK. */
async function importVapidPrivateKey(privateKeyJwk) {
  const jwk = typeof privateKeyJwk === 'string' ? JSON.parse(privateKeyJwk) : privateKeyJwk;
  return crypto.subtle.importKey('jwk', jwk, { name: 'ECDSA', namedCurve: 'P-256' }, false, ['sign']);
}

async function buildVapidHeader(privateKeyJwk, publicKeyB64url, endpoint, subject) {
  const aud = new URL(endpoint).origin;
  const header = { typ: 'JWT', alg: 'ES256' };
  const payload = { aud, exp: Math.floor(Date.now() / 1000) + 12 * 3600, sub: subject };
  const unsigned = `${bytesToB64url(enc(JSON.stringify(header)))}.${bytesToB64url(enc(JSON.stringify(payload)))}`;
  const key = await importVapidPrivateKey(privateKeyJwk);
  // Web Crypto's ECDSA signature is raw r||s (IEEE P1363, 64 bytes for P-256) —
  // exactly the format a JWT ES256 signature needs. No DER conversion required.
  const sig = await crypto.subtle.sign({ name: 'ECDSA', hash: 'SHA-256' }, key, enc(unsigned));
  const jwt = `${unsigned}.${bytesToB64url(new Uint8Array(sig))}`;
  return `vapid t=${jwt}, k=${publicKeyB64url}`;
}

/* ---------- payload encryption (RFC 8291 + RFC 8188 aes128gcm) ---------- */

async function hmac(keyBytes, data) {
  const key = await crypto.subtle.importKey('raw', keyBytes, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  return new Uint8Array(await crypto.subtle.sign('HMAC', key, data));
}
async function hkdfExpand(prk, info, len) {
  // single-block expand — every info string used below fits in one 32-byte block
  const t = await hmac(prk, concatBytes(info, new Uint8Array([1])));
  return t.slice(0, len);
}

async function encryptPayload(subscription, plaintext) {
  const uaPublic = b64urlToBytes(subscription.keys.p256dh);   // 65-byte uncompressed EC point
  const authSecret = b64urlToBytes(subscription.keys.auth);    // 16 bytes

  const uaKey = await crypto.subtle.importKey(
    'raw', uaPublic, { name: 'ECDH', namedCurve: 'P-256' }, false, []
  );
  const serverKeyPair = await crypto.subtle.generateKey({ name: 'ECDH', namedCurve: 'P-256' }, true, ['deriveBits']);
  const serverPublic = new Uint8Array(await crypto.subtle.exportKey('raw', serverKeyPair.publicKey));

  const sharedSecret = new Uint8Array(
    await crypto.subtle.deriveBits({ name: 'ECDH', public: uaKey }, serverKeyPair.privateKey, 256)
  );

  // RFC 8291 section 3.3/3.4 — two chained HKDF stages
  const prkKey = await hmac(authSecret, sharedSecret);
  const keyInfo = concatBytes(enc('WebPush: info\0'), uaPublic, serverPublic);
  const ikm = await hkdfExpand(prkKey, keyInfo, 32);

  const salt = crypto.getRandomValues(new Uint8Array(16));
  const prk = await hmac(salt, ikm);
  const cek = await hkdfExpand(prk, enc('Content-Encoding: aes128gcm\0'), 16);
  const nonce = await hkdfExpand(prk, enc('Content-Encoding: nonce\0'), 12);

  // RFC 8188 single-record body: plaintext + 0x02 delimiter (this is the only/last record)
  const recordPlain = concatBytes(enc(plaintext), new Uint8Array([2]));
  const aesKey = await crypto.subtle.importKey('raw', cek, { name: 'AES-GCM' }, false, ['encrypt']);
  const ciphertext = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv: nonce }, aesKey, recordPlain));

  // aes128gcm header: salt(16) | record size(4, BE) | keyid length(1) | keyid (server public key, 65 bytes)
  const recordSize = new Uint8Array(4);
  new DataView(recordSize.buffer).setUint32(0, 4096);
  const header = concatBytes(salt, recordSize, new Uint8Array([serverPublic.length]), serverPublic);

  return concatBytes(header, ciphertext);
}

/* Sends one push message. Throws on a hard failure; callers are expected to
   inspect the response status themselves (410/404 means "delete this subscription"). */
/* `ttlSeconds` is how long the push service should hold the message for a phone
   that is offline. Peak's copy hardcodes a day, which suits a "log your meals"
   nudge; a toilet reminder that surfaces tomorrow morning is worse than none,
   so Scout passes something much shorter. */
async function sendWebPush(subscription, payloadObj, env, ttlSeconds) {
  const body = await encryptPayload(subscription, JSON.stringify(payloadObj));
  const authHeader = await buildVapidHeader(env.VAPID_PRIVATE_KEY, env.VAPID_PUBLIC_KEY, subscription.endpoint, env.VAPID_SUBJECT);
  return fetch(subscription.endpoint, {
    method: 'POST',
    headers: {
      Authorization: authHeader,
      'Content-Encoding': 'aes128gcm',
      'Content-Type': 'application/octet-stream',
      TTL: String(ttlSeconds == null ? 86400 : ttlSeconds)
    },
    body
  });
}

export { sendWebPush };
